language: java
jdk:
  - oraclejdk8

# sudo required for docker builds  
sudo: required
services:
  - docker

# Chrome required for Karma tests
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

# Current node and Angular-CLI required for Angular build
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

- nvm install --lts=boron
- npm install -g angular-cli
- npm install --prefix angular
- ./angular/build.sh
