#
# Docker compose file for the latest container builds
#
database:
  environment:
    MYSQL_ROOT_PASSWORD: my-secret-pw
  # Expose port 3306 to host. Not for the application but
  # handy to inspect the database from the host machine.
  ports:
    - "3306:3306"
  image: hotblac/spanners-database:latest
  restart: always
api:
  image: hotblac/spanners-api:latest
  links:
    - database:spanners-database
  # Expose service to host. Not for the application but
  # handy to call the API direct from the host machine.
  ports:
    - "8090:8080"
  restart: always
users:
  image: hotblac/spanners-users:latest
  links:
    - database:spanners-database
  # Expose service to host. Not for the application but
  # handy to call the API direct from the host machine.
  ports:
    - "8091:8080"
  restart: always
mvc:
  image: hotblac/spanners-mvc:latest
  links:
    - api:spanners-api
  ports:
    - "8080:8080"
  restart: always