#
# Docker compose file to demonstrate multiple load balanced instances of services
#
version: '2'

services:

  discovery:
      # Expose port 8671 to host. Not for the application but
      # handy to view the Eureka info page from the host machine.
    ports:
      - "8761:8761"
    image: hotblac/disco:latest
    restart: always

  database:
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    image: hotblac/spanners-database:latest
    restart: always

  api1:
    image: hotblac/spanners-api:latest
    links:
      - database:spanners-database
    restart: always
  api2:
    image: hotblac/spanners-api:latest
    links:
      - database:spanners-database
    restart: always
  api3:
    image: hotblac/spanners-api:latest
    links:
      - database:spanners-database
    restart: always

  users1:
    image: hotblac/spanners-users:latest
    links:
      - database:spanners-database
    restart: always
  users2:
    image: hotblac/spanners-users:latest
    links:
      - database:spanners-database
    restart: always
  users3:
    image: hotblac/spanners-users:latest
    links:
      - database:spanners-database
    restart: always

  mvc1:
    image: hotblac/spanners-mvc:latest
    ports:
      - "8080:8080"
    restart: always
  mvc2:
    image: hotblac/spanners-mvc:latest
    ports:
      - "8081:8080"
    restart: always